#!/usr/bin/env tclsh

set env(LD_LIBRARY_PATH) "target/tcl"

# load target/tcl/example1.dylib
# load example1.dylib
# load target/tcl/libexample1.so
load target/tcl/example1.so

cubic_poly 2.3 3.5 7.11 13.17 19.23

