#!/usr/bin/env ruby

ENV["LD_LIBRARY_PATH"] = 'target/ruby'
$:.unshift 'target/ruby'

require 'example1'

puts "EXAMPLE1_VERSION = #{Example1::EXAMPLE1_VERSION}"
puts Example1.cubic_poly(2.0, 3.0, 5.0, 7.0, 11.0)

