#!/usr/bin/env python3.10

import sys
sys.path.append('target/python')

from example2 import Polynomial, VectorDouble

poly = Polynomial()
poly.coeffs = VectorDouble([ 2.0, 3.0, 5.0, 7.0, 11.0, -13.0 ])

print(list(poly.coeffs))
print(poly.evaluate(2.0))

