#!/usr/bin/env ruby

ENV["LD_LIBRARY_PATH"] = 'target/ruby'
$:.unshift 'target/ruby'

require 'example2'
include Example2

p = Polynomial.new
p.coeffs << 3.5
p.coeffs << 7.11
p.coeffs << 13.17
p.coeffs << 19.23

puts p.evaluate(2.3)

########################################
# Extend for convenience:

class Polynomial
  # Constructor:
  def self.[] elems
    elems.inject(new){|this, x| this.coeffs << x; this}
  end
  # Like a Proc:
  def to_proc
    lambda{|x| evaluate(x)}
  end
  alias :call :evaluate
  alias :[]   :evaluate
end

require 'pp'

p = Polynomial[ [3.5, 7.11, 13.17, 19.23] ]
pp p.coeffs.to_a

x = 0..5
pp x.zip(x.map(&p)).to_h

