#!/usr/bin/env ruby

ENV["LD_LIBRARY_PATH"] = 'target/ruby'
$:.unshift 'target/ruby'

require 'example2'
include Example2

p = Polynomial.new
p.coeffs << 3.5
p.coeffs << 7.11
p.coeffs << 13.17
p.coeffs << 19.23

puts p.evaluate(2.3)

########################################
# Extend for convenience:

class Polynomial
  # "Coercer":
  def self.[] elems
    new.tap do | this |
      elems.each{|x| this.coeffs << x}
    end
  end
  # Like a Proc:
  def to_proc
    lambda{|x| evaluate(x)}
  end
  alias :call :evaluate
  alias :[]   :evaluate
end

require 'pp'

p = Polynomial[ [3.5, 7.11, 13.17, 19.23] ]

pp [2, -5, 7, 11].map(&p)

